config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/about'
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  root "home#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true,length: {maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  attachment :profile_image

  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_up_path_for(resource)
     user_path(current_user)
    end
    def after_sign_in_path_for(resource)
     user_path(current_user)
    end

	protected
	def configure_permitted_parameters 
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  def top
  end

  def new
  end

  def create
    @books = Book.all
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book)
    else
     @user = current_user
     render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to book_path(book)
    else
      @book = book
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
    end
	def about
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def follower
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.follower_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
    #@users = User.all
  	@user = User.find(params[:id])
  	@book = Book.new
    @books = @user.books
    #@book = Book.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def info
  	@user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(user)
    else
      @user = user
      render :edit
    end
  end

  def follows
  end

  def followers
  end

  private
  def user_params
   params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_info.html.erb
<h2>User info</h2>
<div>
 <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
</div>

<table class="table" width="600" cellspacing="0" cellpadding="5">
<tr>
<th><font size=3px>name</font></th>
<th width="300"><font size=3px><%= current_user.name %></font></th>
</tr>
<tr>
<th><font size=3px>introduction</font></th>
<th width="300"><font size=3px><%= current_user.introduction %></font></th>
</tr>
<!-- フォロー -->
<tr>
    <th>follows</th>
    <th><%= link_to user.follower.count, user_follows_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followed.count, user_followers_path(user) %></th>
  </tr>
<!-- フォロー -->
</table>

<!-- フォローボタン -->
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
  <% end %>
<% end %>
<!-- フォローボタン -->


    <p>
    <%= link_to "", edit_user_path(current_user), class: "glyphicon glyphicon-wrench btn btn-default btn-block" %>
    </p>

app/views/books/_new.html.erb
<h2>New book</h2>

<%= form_for(book) do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title, class: "col-xs-12" %>

  <h4>Body</h4>
  <%= f.text_area :body, class: "col-xs-12" %><br>
 
  <%= f.submit 'Create Book', class: "cbotn btn btn-primary btn-block active" %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="error_explanation">
  <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">

<h2>Editing Book</h2>
<%= form_for(@book) do |f| %>
  <div>
    <label>Title</label>
    <div>
    <%= f.text_field :title, autofocus: true, class: "col-xs-12" %>
  </div>
  </div>
  <div>
    <label>Opinion</label>
    <div>
     <%= f.text_area :body, autofocus: true, class: "col-xs-12" %>
    </div>
  </div>
  <%= f.submit "Update Book",  class: "botn btn btn-primary btn-block" %>
<% end %>

<%= link_to "Show", book_path(@book) %>
|
<a href="/books">Back</a>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="error_explanation">
  <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
　<div class="row">
  <div class="col-xs-3">
    <%= render 'info', user: @user %>
    <%= render 'books/new', book: @book %>
    </div>
   <div class="col-xs-9"> 

<h2>Books</h2>

<table class="table" width="600" cellspacing="0" cellpadding="5" >

<tr>
<th width="200"><font></font></th>
<th width="200"><font>Title</font></th>
<th width="400"><font>Opinion</font></th>
</tr>

<% @books.each do |book| %>

<tr>
<td align="left" width="200">
	<%= link_to user_path(book.user) do %>
	<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
	<% end %>
</td>
<td align="left" width="200"><%= link_to book.title, book_path(book) %></td>
<td valign="top" width="400"><%= book.body %></td>
<!-- いいね機能 -->
<td valign="top" width="400">
<%= link_to book_path(book.id) do %>
  <span class="glyphicon glyphicon-heart" aria-hidden="true"><%=  "#{book.favorites.count} " %></span>
<% end %>
</td>
<!-- いいね機能 -->
<!-- コメント機能 -->
<td valign="top" width="400"><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
<!-- コメント機能 -->
</tr>

<% end %>

</table>


</div>
 　</div>
 </div>

app/views/books/show.html.erb
<div class="container">
　<div class="row">
	<div class="col-xs-3">
      <%= render 'users/info', user: @book.user %>
      <%= render 'books/new', book: @book_new %>
    </div>
   <div class="col-xs-9"> 

<h1>Book detail</h1>

<table class="table" width="650" cellspacing="0" cellpadding="5" >
<tr>
<th width="200"><font></font></th>
<th width="100"><font></font></th>
<th width="100"><font></font></th>
<th width="50"><font></font></th>
<th width="50"><font></font></th>
<th width="50"><font></font></th>
<th width="100"><font></font></th>
</tr>

<tr>
<td align="left" width="200">
	<%= link_to user_path(@user) do %>
	<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <br>
  <%= link_to @user.name, user_path(@user) %>
	<% end %>
</td>
<td align="left" width="100"><%= link_to @book.title, book_path(@book) %></td>
<td valign="top" width="100"><%= @book.body %></td>


<% if @book.user == current_user %>
    <td valign="top" width="50"><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %></td>
    <td valign="top" width="50"><%= link_to "Destroy", book_path(@book), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %></td>
<% end %>

<td valign="top" width="50">
<!-- いいね機能 -->
<% if @book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(@book), method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= @book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(@book), method: :post do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= @book.favorites.count %>
  <% end %>
<% end %>
<!-- いいね機能 -->
</td>


<td valign="top" width="100"><%= @book.book_comments.count %>件コメント</td>

</tr>

</table>


<!-- コメント機能 -->

  <ol>
  <% @book.book_comments.each do |book_comment| %>
    <li class="comment">
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
            <%= image_tag('sample-author1.jpg', style: "width: 60px; height: 60px;") %>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= book_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= book_comment.comment %></div>
          <% if book_comment.user == current_user %>
            <div>
              <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
            </div>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ol>

<!-- <form class="mt-20"> -->
<%= form_for [@book, @book_comment] do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<!-- </form> -->

<!-- コメント機能 -->

</div>
 　</div>
 </div>

app/views/home/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/home/top.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>
welcome to <span class="glyphicon glyphicon-book">Bookers</span> !!
</h1>
<p>In <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span>,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

<div>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block active" %>
</div>
<div>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block active" %>
</div>

</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
       <nav class="nav navbar-nav navbar-left">
        <span class="bookers-title">Bookers</span>
       </nav>

    <div id="slidemenu">
     <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
      <li class="">
        <%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <%= link_to "Users", users_path, class: "glyphicon glyphicon-user" %>
      </li>
      <li class="">
        <%= link_to "Books", books_path, class: "glyphicon glyphicon-book" %>
      </li>
      <li class="">
        <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
      </li>
    <% else %>
      <li class="">
        <%= link_to "Home", root_path, class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <%= link_to "About", home_about_path, class: "glyphicon glyphicon-link" %>
      </li>
      <li class="">
        <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
      </li>
      <li class="">
        <%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-out" %>
      </li>
    <% end %>
     </ul>
    </div>
     
      
     </div>
    </header>
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/followed.html.erb
<h2>Follower Users</h2>
<% if @users.count > 0 %>

<table class="table" width="925" cellspacing="0" cellpadding="5" >
<tr>
<th width="200"><font>image</font></th>
<th width="400"><font>name</font></th>
<th width="100"><font>name</font></th>
<th width="100"><font>name</font></th>
<th width="100"><font></font></th>
<th width="25"><font></font></th>
</tr>

<% @users.each do |user| %>

<tr>
<td align="left" width="200"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
<td valign="top" width="400"><%= user.name %></td>
<td valign="top" width="100">フォロー数：<%= user.follower.count %></td>
<td valign="top" width="100">フォロワー数：<%= user.followed.count %></td>
<td valign="top" width="25"><%= link_to "Show", user_path(user) %></td>
</tr>

<% end %>

</table>

<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/follower.html.erb
<h2>Follower Users</h2>
<% if @users.count > 0 %>

<table class="table" width="925" cellspacing="0" cellpadding="5" >
<tr>
<th width="200"><font>image</font></th>
<th width="400"><font>name</font></th>
<th width="100"><font>name</font></th>
<th width="100"><font>name</font></th>
<th width="100"><font></font></th>
<th width="25"><font></font></th>
</tr>

<% @users.each do |user| %>

<tr>
<td align="left" width="200"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
<td valign="top" width="400"><%= user.name %></td>
<td valign="top" width="100">フォロー数：<%= user.follower.count %></td>
<td valign="top" width="100">フォロワー数：<%= user.followed.count %></td>
<td valign="top" width="25"><%= link_to "Show", user_path(user) %></td>
</tr>

<% end %>

</table>


<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_info.html.erb
<h2>User info</h2>
<div>
 <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
</div>

<table class="table" width="600" cellspacing="0" cellpadding="5">
<tr>
<th><font size=3px>name</font></th>
<th width="300"><font size=3px><%= user.name %></font></th>
</tr>
<tr>
<th><font size=3px>introduction</font></th>
<th width="300"><font size=3px><%= user.introduction %></font></th>
</tr>
<!-- フォロー -->
<tr>
    <th>follows</th>
    <th><%= link_to user.follower.count, user_follows_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followed.count, user_followers_path(user) %></th>
  </tr>
<!-- フォロー -->
</table>

<!-- フォローボタン -->
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
  <% end %>
<% end %>
<!-- フォローボタン -->

<p>
  <%= link_to "", edit_user_path(user), class: "glyphicon glyphicon-wrench btn btn-default btn-block" %>
</p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="error_explanation">
  <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>User info</h2>
<%= form_for(@user) do |f| %>
  <div>
    <label>Name</label>
    <%= f.text_field :name, autofocus: true%>
  </div>
  <div>
    <label>Image</label>
     <%= f.attachment_field :profile_image %>
  </div>
  <div>
    <label>Introduction</label>
    <%= f.text_area :introduction, autofocus: true%>
  </div>
  <%= f.submit "Update User", class: "btn btn-default active"%>
<% end %>

app/views/users/index.html.erb
<div class="container">
　<div class="row">
	<div class="col-xs-3">
      <%= render 'books/info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
   <div class="col-xs-9"> 

<h1>Users</h1>

<table class="table" width="925" cellspacing="0" cellpadding="5" >
<tr>
<th width="200"><font>image</font></th>
<th width="400"><font>name</font></th>
<th width="100"><font>name</font></th>
<th width="100"><font>name</font></th>
<th width="100"><font></font></th>
<th width="25"><font></font></th>
</tr>

<% @users.each do |user| %>

<tr>
<td align="left" width="200"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
<td valign="top" width="400"><%= user.name %></td>
<td valign="top" width="100">フォロー数：<%= user.follower.count %></td>
<td valign="top" width="100">フォロワー数：<%= user.followed.count %></td>
<td valign="top" width="100">
<% if current_user.following?(user) %>
   <%= link_to 'フォロー外す', user_relationships_path(user.id) , method: :delete %>
<% else %>
   <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
<% end %>
</td>
<td valign="top" width="25"><%= link_to "Show", user_path(user) %></td>
</tr>

<% end %>

</table>


</div>
 　</div>
 </div>

app/views/users/show.html.erb
<div class="container">
　<div class="row">
	<div class="col-xs-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
   <div class="col-xs-9"> 

<h2>Books</h2>

<table class="table" width="600" cellspacing="0" cellpadding="5" >

<tr>
<th width="200"><font></font></th>
<th width="200"><font>Title</font></th>
<th width="400"><font>Opinion</font></th>
</tr>

<% @books.each do |book| %>

<tr>
<td align="left" width="200">
	<%= link_to user_path(book.user) do %>
	<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
	<% end %>
</td>
<td align="left" width="200"><%= link_to book.title, book_path(book) %></td>
<td valign="top" width="400"><%= book.body %></td>
</tr>

<% end %>

</table>

</div> 
 　</div>
 </div>